import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
const schema={
 persone:['id','cognome','nome','eta','codice_settore','unita','codice_ruolo','turno','indice_operativo'],
 settori:['codice_settore','settore','livello_rad'],
 unita_abitative:['unita','tipo_unita','capacita_unita'],
 ruoli:['codice_ruolo','ruolo','descrizione_ruolo'],
 turni:['turno','orario_turno']
};
const presets=[
{id:'tecnici',title:'Tutti i Tecnici',tag:'MISSIONE 01',description:'Elenca tutte le persone con ruolo di Tecnico.',sql:`SELECT p.id,p.cognome,p.nome,p.eta,s.settore,r.ruolo,p.unita,p.turno,p.indice_operativo\nFROM persone p JOIN settori s ON p.codice_settore=s.codice_settore JOIN ruoli r ON p.codice_ruolo=r.codice_ruolo\nWHERE r.ruolo='Tecnico' ORDER BY p.cognome,p.nome;`},
{id:'under30',title:'Persone con meno di 30 anni',tag:'MISSIONE 02',description:'Trova tutte le persone sotto i 30 anni.',sql:`SELECT id,cognome,nome,eta,codice_settore,unita,codice_ruolo\nFROM persone WHERE eta<30 ORDER BY eta,cognome,nome;`},
{id:'a014',title:'Assegnati all’unità A-014',tag:'MISSIONE 03',description:'Trova chi è assegnato ad A-014.',sql:`SELECT p.id,p.cognome,p.nome,p.eta,p.unita,r.ruolo,s.settore\nFROM persone p JOIN ruoli r ON p.codice_ruolo=r.codice_ruolo JOIN settori s ON p.codice_settore=s.codice_settore\nWHERE p.unita='A-014' ORDER BY p.cognome,p.nome;`},
{id:'luca',title:'Codice operativo di Luca Bianchi',tag:'MISSIONE 04',description:'Cerca Luca Bianchi nel registro.',sql:`SELECT id,cognome,nome,indice_operativo FROM persone\nWHERE lower(nome)='luca' AND lower(cognome)='bianchi';`},
{id:'duplicati',title:'Nomi registrati più volte',tag:'ANOMALIA',description:'Evidenzia nome+cognome presenti più di una volta.',sql:`SELECT cognome,nome,COUNT(*) AS occorrenze\nFROM persone GROUP BY cognome,nome HAVING COUNT(*)>1 ORDER BY occorrenze DESC,cognome,nome;`},
{id:'q1',title:'Query 1 · Persone per Settore + radiazioni',tag:'PPTX · QUERY 01',description:'Numero di persone per settore e relativo livello di radiazioni.',sql:`SELECT s.settore,s.livello_rad,COUNT(p.id) AS numero_persone\nFROM persone p INNER JOIN settori s ON p.codice_settore=s.codice_settore\nGROUP BY s.settore,s.livello_rad ORDER BY COUNT(p.id) DESC;`},
{id:'q2',title:'Query 2 · Turno + Ruolo + indice medio',tag:'PPTX · QUERY 02',description:'Distribuzione del personale per turno e ruolo con indice medio.',sql:`SELECT t.orario_turno,r.ruolo,COUNT(p.id) AS totale_addetti,ROUND(AVG(p.indice_operativo),2) AS indice_medio\nFROM persone p INNER JOIN turni t ON p.turno=t.turno INNER JOIN ruoli r ON p.codice_ruolo=r.codice_ruolo\nGROUP BY t.orario_turno,r.ruolo ORDER BY t.orario_turno;`},
{id:'q3',title:'Query 3 · Forza operativa per Settore + Ruolo',tag:'PPTX · QUERY 03',description:'Addetti e indice medio per settore e ruolo.',sql:`SELECT s.settore,r.ruolo,COUNT(p.id) AS numero_addetti,ROUND(AVG(p.indice_operativo),2) AS indice_medio\nFROM persone p INNER JOIN settori s ON p.codice_settore=s.codice_settore INNER JOIN ruoli r ON p.codice_ruolo=r.codice_ruolo\nGROUP BY s.settore,r.ruolo ORDER BY s.settore ASC,COUNT(p.id) DESC;`}
];
function App(){
 const[sql,setSql]=useState(presets[0].sql),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[active,setActive]=useState('tecnici'),[tab,setTab]=useState('presets');
 const[table,setTable]=useState('persone'),[columns,setColumns]=useState(['*']),[filters,setFilters]=useState([{field:'',op:'=',value:''}]),[order,setOrder]=useState(''),[limit,setLimit]=useState('100');
 const[selectedMission,setSelectedMission]=useState(null);
 useEffect(()=>{const move=e=>document.documentElement.style.setProperty('--mx',`${e.clientX}px`); window.addEventListener('pointermove',move); return()=>window.removeEventListener('pointermove',move)},[]);
 useEffect(()=>{setColumns(['*']);setFilters([{field:'',op:'=',value:''}]);},[table]);
 const generated=useMemo(()=>{const cols=columns.includes('*')?'*':columns.join(', ');let q=`SELECT ${cols}\nFROM ${table}`;const v=filters.filter(f=>f.field&&f.value!=='');if(v.length)q+='\nWHERE '+v.map(f=>{const val=f.value.replaceAll("'","''");const numeric=['eta','id','indice_operativo','livello_rad','capacita_unita'].includes(f.field)&&!isNaN(Number(f.value));const rhs=['IS NULL','IS NOT NULL'].includes(f.op)?'':numeric?f.value:`'${val}'`;return `${f.field} ${f.op}${rhs?' '+rhs:''}`}).join('\n  AND ');if(order)q+=`\nORDER BY ${order}`;if(limit)q+=`\nLIMIT ${Math.min(1000,Math.max(1,Number(limit)||100))}`;return q+';'},[table,columns,filters,order,limit]);
 function addFilter(){setFilters([...filters,{field:'',op:'=',value:''}])}; function uf(i,k,v){setFilters(filters.map((f,j)=>j===i?{...f,[k]:v}:f))}
 async function runQuery(){if(!supabase){setError('Configura VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY.');return}setBusy(true);setError('');setRows([]);const r=await supabase.rpc('execute_sql',{query_text:sql});if(r.error)setError(r.error.message);else setRows(Array.isArray(r.data)?r.data:r.data?[r.data]:[]);setBusy(false);setTimeout(()=>document.querySelector('.results')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
 const choose=p=>{setActive(p.id);setSql(p.sql);setRows([]);setError('');setSelectedMission(p.id);setTimeout(()=>document.querySelector('.query-deck')?.scrollIntoView({behavior:'smooth',block:'center'}),80)};
 return <div className="app">
  <div className="space-noise"/><div className="aurora-ribbon a1"/><div className="aurora-ribbon a2"/><div className="aurora-ribbon a3"/><div className="stars s1"/><div className="stars s2"/><div className="cursor-glow"/>
  <header className="hero-cockpit">
   <div className="topline"><span>◆ AURORA II / ANAGRAFE CENTRALE</span><span className="signal"><i/> LINK STABILE · 2187.04.17</span></div>
   <div className="hero-stage">
    <div className="planet"><div className="planet-glow"/><div className="continent c1"/><div className="continent c2"/><div className="cityline"/></div>
    <div className="orbit o1"/><div className="orbit o2"/><div className="core"><span className="core-ring r1"/><span className="core-ring r2"/><b>AI</b><small>ARCHIVIO</small></div>
    <div className="hero-copy"><span className="eyebrow">COLONIA AURORA II · ANNO 2187</span><h1>THE <em>AURORA</em><br/><strong>QUERY CONSOLE</strong></h1><p>Il registro anagrafico è collassato. <b>Tu sei l'operatore.</b><br/>Ricostruisci la colonia interrogando ciò che è rimasto.</p><div className="hero-actions"><button className="primary-cta" onClick={()=>document.querySelector('.mission-deck')?.scrollIntoView({behavior:'smooth'})}>ENTRA NEL REGISTRO <span>↓</span></button><div className="micro-status"><span/> DATABASE ONLINE<br/><small>5 RELAZIONI · ACCESSO READ-ONLY</small></div></div></div>
    <div className="hud-card left"><span>FLUSSO DATI</span><b>98.7%</b><div className="bars"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div>
    <div className="hud-card right"><span>RADIAZIONE</span><b>0.42 mSv</b><small>SETTORE AURORA</small><div className="pulse-line"/></div>
   </div>
   <div className="incident"><span className="incident-dot"/> INCIDENTE ANAGRAFICO <b>·</b> ARCHIVIO CENTRALE OFFLINE <b>·</b> 200 SCHEDE RECUPERATE <b>·</b> PROCEDURA DI RICOSTRUZIONE ATTIVA</div>
  </header>
  <main>
   <section className="mission-deck">
    <div className="section-heading"><div><span className="section-no">01 / OPERAZIONI</span><h2>Le richieste dell'Ufficio Centrale</h2><p>Non sono semplici pulsanti. Sono i primi ordini di missione.</p></div><div className="stamp">AUTHORIZED<br/><b>QUERY OPS</b><br/>AURORA II</div></div>
    <div className="mission-grid">{presets.map((p,i)=><button className={'mission-card '+(active===p.id?'selected':'')} key={p.id} onClick={()=>choose(p)}><span className="mission-number">{String(i+1).padStart(2,'0')}</span><span className="mission-tag">{p.tag}</span><span className="mission-icon">{['◈','◇','⌂','◎','⚠','◒','◓','◑'][i]}</span><strong>{p.title}</strong><small>{p.description}</small><span className="mission-line"/><span className="mission-go">APRI MISSIONE ↗</span></button>)}</div>
   </section>
   <section className="query-deck">
    <div className="deck-head"><div><span className="section-no">02 / QUERY DECK</span><h2>Centro di controllo</h2></div><div className="mode-switch"><button className={tab==='presets'?'active':''} onClick={()=>setTab('presets')}>MISSIONI</button><button className={tab==='builder'?'active':''} onClick={()=>setTab('builder')}>BUILDER</button><button className={tab==='sql'?'active':''} onClick={()=>setTab('sql')}>SQL</button></div></div>
    {tab==='builder'&&<section className="builder glass-panel"><div className="panel-title"><div><span className="tiny-label">VISUAL QUERY ENGINE</span><h3>Costruisci la richiesta</h3></div><button className="run secondary" onClick={()=>{setSql(generated);setActive('');setTab('sql')}}>TRASFERISCI → SQL</button></div><div className="builder-row"><label>Tabella<select value={table} onChange={e=>setTable(e.target.value)}>{Object.keys(schema).map(t=><option key={t}>{t}</option>)}</select></label><label>Ordinamento<select value={order} onChange={e=>setOrder(e.target.value)}><option value="">— nessuno —</option>{schema[table].map(c=><React.Fragment key={c}><option value={`${c} ASC`}>{c} ↑</option><option value={`${c} DESC`}>{c} ↓</option></React.Fragment>)}</select></label><label>Limite<input type="number" min="1" max="1000" value={limit} onChange={e=>setLimit(e.target.value)}/></label></div><div className="field-list"><label>Campi da visualizzare</label><div className="checks"><label><input type="checkbox" checked={columns.includes('*')} onChange={()=>setColumns(columns.includes('*')?schema[table].slice(0,4):['*'])}/> tutti</label>{schema[table].map(c=><label key={c}><input type="checkbox" checked={columns.includes(c)} disabled={columns.includes('*')} onChange={e=>setColumns(e.target.checked?[...columns.filter(x=>x!=='*'),c]:columns.filter(x=>x!==c))}/>{c}</label>)}</div></div><div className="filters"><div className="filter-head"><label>Filtri</label><button onClick={addFilter}>+ AGGIUNGI</button></div>{filters.map((f,i)=><div className="filter" key={i}><select value={f.field} onChange={e=>uf(i,'field',e.target.value)}><option value="">campo…</option>{schema[table].map(c=><option key={c}>{c}</option>)}</select><select value={f.op} onChange={e=>uf(i,'op',e.target.value)}><option>=</option><option>!=</option><option>&gt;</option><option>&lt;</option><option>&gt;=</option><option>&lt;=</option><option>IS NULL</option><option>IS NOT NULL</option></select><input value={f.value} placeholder="valore…" onChange={e=>uf(i,'value',e.target.value)}/>{filters.length>1&&<button className="remove" onClick={()=>setFilters(filters.filter((_,j)=>j!==i))}>×</button>}</div>)}</div></section>}
    {tab==='sql'&&<section className="sqlpanel glass-panel"><div className="panel-title"><div><span className="tiny-label">DIRECT LINK</span><h3>Scrivi la tua query</h3></div><span className="hint">SELECT / WITH · SOLA LETTURA</span></div><textarea value={sql} onChange={e=>{setSql(e.target.value);setActive('')}} spellCheck="false"/><button className="run" onClick={runQuery}>{busy?'ESECUZIONE…':'▶ ESEGUI QUERY'}</button></section>}
    <section className="signal-panel glass-panel"><div className="signal-head"><div><span className="tiny-label">03 / TRANSMISSION</span><h3>La query che verrà inviata al nucleo dati</h3></div><div className="live-dot"><i/> LIVE</div></div><div className="code-frame"><div className="code-top"><span>QUERY_PACKET.aurora</span><span>READ ONLY · ENCRYPTED</span></div><pre>{sql}</pre><div className="scan-bar"/></div><button className="execute" onClick={runQuery} disabled={busy}><span>{busy?'PROCESSING':'EXECUTE'}</span><b>↗</b></button></section>
   </section>
   <section className="results glass-panel"><div className="result-orb"><span>DATA</span><b>{rows.length||'—'}</b><small>ROWS</small></div><div className="panel-title"><div><span className="tiny-label">04 / RECOVERY</span><h3>{rows.length?`${rows.length} righe recuperate`:'Nessun dato recuperato'}</h3><p className="result-sub">{error?'Il nucleo ha rifiutato il pacchetto.':rows.length?'Trasmissione ricevuta dal registro centrale.':'Esegui una missione per interrogare l’archivio.'}</p></div>{rows.length>0&&<button className="ghost" onClick={()=>setRows([])}>RESET</button>}</div>{error&&<div className="error">⚠ {error}</div>}{!error&&rows.length>0?<div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{Object.keys(rows[0]).map(k=><td key={k}>{r[k]===null?'—':String(r[k])}</td>)}</tr>)}</tbody></table></div>:!error&&<div className="empty"><span>◇</span><div>IL REGISTRO STA ASPETTANDO LA TUA QUERY</div><small>Seleziona una missione sopra e invia il pacchetto al database.</small></div>}</section>
   <section className="schema-panel"><div className="section-heading"><div><span className="section-no">05 / ARCHITECTURE</span><h2>Anatomia del registro</h2><p>Le cinque relazioni che tengono in vita Aurora II.</p></div></div><div className="schema-map"><div className="schema-center"><span>PERSONE</span><small>registro centrale</small></div>{Object.entries(schema).filter(([t])=>t!=='persone').map(([t,c],i)=><div className={'schema-node n'+i} key={t}><b>{t}</b><small>{c.slice(0,4).join(' · ')}</small><i/></div>)}<div className="connector x1"/><div className="connector x2"/><div className="connector x3"/><div className="connector x4"/></div></section>
  </main>
  <footer><span>AURORA II / 2187</span><span>ANAGRAFE CENTRALE · QUERY OPERATIONS</span><span>© DATABASE DIDATTICO</span></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
